# Use this compose file for active development activities.
services:
  audio-producer:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
      ## Application configuration (override these with your values)
      # - ALBUM="My Podcast Album"
      # - GENRE=Podcast
      # - TITLE_SUFFIX=" Â· My Show"
    volumes:
      - ./tmp/cover.jpg:/app/media/default_cover.jpg
    restart: unless-stopped
    develop:
      # enable with `docker compose up --watch`
      watch:
        - path: ./backend
          action: sync+restart
          target: /app/backend
        - path: ./frontend
          action: sync
          target: /app/static
